spring:
  profiles:
    active:
    -  dev
---
spring:
  profiles: dev
  application:
    name: pltservicecloud-config-plt-dev
---
spring:
  profiles: test
  application:
    name: pltservicecloud-config-plt-test