spring:
  profiles:
    active:
    -  dev
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.plt.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  profiles: dev
  application:
    name: pltservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/clouddb01?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/
  instance:
    instance-id: pltservicecloud-dept8001
    prefer-ip-address: true

#info:
#  app.name: pltservicecloud
#  company.name: www.ncr.com
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$
info:
  app.name: pltservicecloud
  company.name: www.atguigu.com
  build.artifactId: pltservicecloud
  build.version: 1.0-SNAPSHOT



---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.plt.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  profiles: test
  application:
    name: pltservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/clouddb01?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/
  instance:
    instance-id: pltservicecloud-dept8001
    prefer-ip-address: true

#info:
#  app.name: pltservicecloud
#  company.name: www.ncr.com
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$
info:
  app.name: pltservicecloud
  company.name: www.atguigu.com
  build.artifactId: pltservicecloud
  build.version: 1.0-SNAPSHOT

